import { GoogleGenAI } from "@google/genai";
import { ImageSize, ASPECT_RATIO_MAP } from '../types';

// Initialize the client
// The API key must be provided via environment variable
const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

/**
 * Generates an image using the Google Gemini Imagen model.
 * 
 * @param prompt The text description for the image.
 * @param size The requested size (maps to aspect ratio).
 * @returns A Promise resolving to the base64 data URL of the generated image.
 */
export const generateImage = async (prompt: string, size: ImageSize): Promise<string> => {
  try {
    const aspectRatio = ASPECT_RATIO_MAP[size] || '1:1';
    
    // Using 'imagen-4.0-generate-001' for high quality results
    const modelName = 'imagen-4.0-generate-001'; 

    const response = await ai.models.generateImages({
      model: modelName,
      prompt: prompt,
      config: {
        numberOfImages: 1,
        outputMimeType: 'image/jpeg',
        aspectRatio: aspectRatio,
      },
    });

    const generatedImages = response.generatedImages;
    
    if (!generatedImages || generatedImages.length === 0) {
      throw new Error("No image generated by the API.");
    }

    const base64ImageBytes = generatedImages[0].image.imageBytes;
    // Construct the Data URL
    const imageUrl = `data:image/jpeg;base64,${base64ImageBytes}`;
    
    return imageUrl;

  } catch (error: any) {
    console.error("API Generation Error:", error);
    const message = error.message || "Failed to generate image. Please try again.";
    throw new Error(message);
  }
};